import { StyleSheet } from 'react-native';

import { colors, spacing } from '../../ui';

export const styles = StyleSheet.create({
  scroll: {
    flex: 1,
    backgroundColor: colors.background,
  },
  content: {
    gap: spacing.md,
    padding: spacing.md,
    paddingBottom: spacing.xl,
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  headerLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.sm,
  },
  modelBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.xs,
    paddingHorizontal: spacing.sm,
    paddingVertical: 4,
    borderRadius: 9999,
    backgroundColor: colors.surfaceChip,
  },
  liveDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: colors.accent,
  },
  subtitleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.sm,
  },
  card: {
    gap: spacing.sm,
    width: '100%',
    padding: spacing.md,
    borderRadius: 12,
    backgroundColor: colors.surfaceRow,
  },
  cardHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  cardHeaderLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.sm,
  },
  levelPill: {
    paddingHorizontal: spacing.sm,
    paddingVertical: 2,
    borderRadius: 4,
    backgroundColor: colors.accent,
  },
  segmented: {
    flexDirection: 'row',
    gap: spacing.sm,
    padding: 6,
    borderRadius: 12,
    backgroundColor: colors.surfaceRow,
  },
  segmentedOption: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: spacing.sm,
    minHeight: 58,
    borderRadius: 8,
  },
  segmentedOptionActive: {
    backgroundColor: colors.surfaceMuted,
  },
  curvatureRow: {
    flexDirection: 'row',
    gap: spacing.sm,
  },
  curvatureOption: {
    flex: 1,
    height: 40,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 4,
    backgroundColor: colors.surfaceRaised,
  },
  curvatureOptionActive: {
    backgroundColor: colors.accent,
  },
  presetsRow: {
    flexDirection: 'row',
    gap: spacing.sm,
  },
  presetOption: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    minHeight: 52,
    borderRadius: 8,
    backgroundColor: colors.surfaceRaised,
  },
  presetOptionActive: {
    backgroundColor: colors.accent,
  },
  stepper: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: spacing.sm,
    paddingVertical: spacing.sm,
    borderRadius: 8,
    backgroundColor: colors.surfaceRaised,
  },
  stepperButton: {
    width: 48,
    height: 48,
    borderRadius: 8,
    backgroundColor: colors.surfaceChip,
    alignItems: 'center',
    justifyContent: 'center',
  },
  stepperValue: {
    alignItems: 'center',
  },
  optionRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: 14,
    borderRadius: 8,
    backgroundColor: colors.surfaceRaised,
  },
  optionRowLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.md,
    flexShrink: 1,
  },
  optionTexts: {
    flexShrink: 1,
    gap: 2,
  },
  checkMark: {
    width: 22,
    height: 22,
    borderRadius: 6,
    alignItems: 'center',
    justifyContent: 'center',
  },
  checkMarkOn: {
    backgroundColor: colors.accent,
  },
  checkMarkOff: {
    borderWidth: 1,
    borderColor: colors.textDense,
  },
  poiRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.md,
    padding: spacing.sm,
    borderRadius: 8,
    backgroundColor: colors.surfaceRaised,
  },
  promptInputWrapper: {
    position: 'relative',
    justifyContent: 'center',
  },
  promptInput: {
    minHeight: 56,
    borderRadius: 8,
    backgroundColor: colors.surfaceRaised,
    paddingHorizontal: spacing.sm,
    paddingRight: 56,
    color: colors.textPrimary,
    fontSize: 14,
  },
  micButton: {
    position: 'absolute',
    right: spacing.xs,
    width: 40,
    height: 40,
    borderRadius: 6,
    backgroundColor: colors.surfaceChip,
    alignItems: 'center',
    justifyContent: 'center',
  },
  corridorEstimate: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: spacing.sm,
    paddingVertical: spacing.sm,
    borderRadius: 8,
    backgroundColor: colors.surfaceRow,
  },
  corridorEstimateLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.xs,
  },
  generateButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: spacing.sm,
    height: 64,
    borderRadius: 12,
    backgroundColor: colors.accent,
  },
});
